### ISSUE TITLE
LSO Grading

### ISSUE THREAD

**Issue by Heater711** [xenPanda/DCS_Stats#1] opened 2020-11-25 19:26 UTC
Hi,
do not export the LSO grades... is there a solution ?

**Comment by xenPanda** [comment] 2020-11-25 20:07
Please give more specifics. 
Is everything setup? Does the database get the data?
SLMOD handles capturing the Super Carrier grades and this code sends it and the other stats to a MySql database that needs to be setup. This does not interface with the AirBoss script form MOOSE at this time.

**Comment by Heater711** [comment] 2020-11-25 21:17
yeas, everything in setup. DB takes the datas. I've try to land with SC CASE I radio procedure without success. 

Maybe I need to unistall Airboss from the mission ?

**Comment by xenPanda** [comment] 2020-11-25 21:39
Probably. Sounds like an issue with AirBoss and Super Carrier. I have had similar issues with Super Carrier when running the AirBoss script. That is an issue between them and isn't anything I can do about it in my code. I made look into adding in the AirBoss grades later if/when I feel SC and AB are playing nice together.

**Comment by Heater711** [comment] 2020-11-26 16:38
Hi, I've found this error on log (AB and Moose disable)

431.149  SLMOD ERROR: slmod.scheduleFunction, error in scheduled function: [string "C:\Users\Administrator\Saved Games\syriaprivate\Scripts/net/Slmodv7_6/SlmodStats.lua"]:400: attempt to index local 'mStats' (a nil value)

**Comment by xenPanda** [comment] 2020-11-26 17:17
First off the instructions indicate that this code works with SLMOD 7.5. There are known issues with 7.6 and this branch. There is a branch for 7.6 code that is working for me, but I have not merged it with the master branch. Secondly that error has to do with SLMOD installation and not this code, you will need to check with them for any issues, I cannot support their code. However nil value errors are often related to missionscripting.lua sanitization. SLMOD rewrites this file during install so I am not sure why there would be an issue, but I suggest checking there forums.

**Comment by Heater711** [comment] 2020-11-29 11:13
Okay, I'm rolling back with SLMOD 7.5, install goes fine, MOOSE unistalled and launched a simple missioni with SC on my server.
No grades goes on the database. I will try with Stennis next time

**Comment by xenPanda** [comment] 2020-11-29 15:17
The stennis probably won't work. The script was designed for Super Carrier.

Is DCS giving you a grade on screen when you land? There are a couple of
things to check.

Check dcs.log for LSO grades to see if they are being recorded by DCS. Then
if they are check /scripts/slmod/slmodstats.lua and look for LSO grades
there.

If you can post the logs here I will have a look.

**Comment by Heater711** [comment] 2020-11-29 22:36
no Grade on dcs.log

line 29 there is (debiref log)

[debrief.log](https://github.com/xenPanda/DCS_Stats/files/5612960/debrief.log)
[dcs.log](https://github.com/xenPanda/DCS_Stats/files/5612959/dcs.log)

**Comment by xenPanda** [comment] 2020-11-30 07:15
The dcs.log is an indicator of the last time you ran DCS as it is cleared out after every restart, so it appears during the last instance of DCS running there were not any traps. Please upload the file C:\Users\Andrea\Saved Games\DCS.openbeta\Slmod\SlmodStats.lua 

This will better indicate where the problem is. If there are traps recorded in this file but not in the database then likely the python script is erroring out. If that is the case then the best thing to do is to manually run the script in a console window so you can see what the error is. 

The slmod7.6 branch was created to solve errors that were happening with that version of slmod and is backwards compatible so you may want to try that code...currently I am managing sites running both versions of the code successfully based on the version of slmod being used.

**Comment by Heater711** [comment] 2021-03-09 10:18
[dcs.log](https://github.com/xenPanda/DCS_Stats/files/6107730/dcs.log) LSO line 1022
[SlmodStats.zip](https://github.com/xenPanda/DCS_Stats/files/6107732/SlmodStats.zip)

Hi, Stats do not extract the LSO line in dcs.log

**Comment by Heater711** [comment] 2021-03-09 10:43
New clean mission without AirBoss, same issue. SlmodStats record only the main event like Takeoff and Land

**Comment by xenPanda** [comment] 2021-03-09 18:56
The issue you are having appears to be with slmod and not this script since slmod doesn't show the LSO grades. Looking at your slmodstats.lua it appears to be incomplete. The entries you have are what normally appears while DCS is running. It is like a running tally of what happened. Slmod needs to summarize the data in order for the script to gather it and send it to the database. I need a more mature slmodstat.lua file in order to be able to troubleshoot more. Get several flights worth of data including some air to air, air to ground, and some traps. Don't worry about running the script file until you have an Slmodstats.lua file that looks similar to the one below. Over the course of time collecting data be sure to stop DCS and restart it several different times as this might be when Slmod correlates the data it has collected.

Here is what the Slmodstats.lua should look similar to. 

`   stats = {
 ["8502672f5e3b83d5be49924a5ddc129f"] = 
    {
        ["times"] = 
        {
            ["SA342M"] = 
            {
                ["total"] = 3662.064,
                ["inAir"] = 2051.09,
                ["weapons"] = 
                {
                    ["HOT3"] = 
                    {
                        ["hit"] = 1,
                        ["kills"] = 1,
                        ["shot"] = 1,
                        ["numHits"] = 1,
                    }, -- end of ["HOT3"]
                }, -- end of ["weapons"]
                ["actions"] = 
                {
                    ["landing"] = 
                    {
                        ["austere"] = 2,
                    }, -- end of ["landing"]
                }, -- end of ["actions"]
                ["kills"] = 
                {
                    ["Ground Units"] = 
                    {
                        ["APCs"] = 1,
                        ["total"] = 1,
                    }, -- end of ["Ground Units"]
                }, -- end of ["kills"]
            }, -- end of ["SA342M"]
            ["SA342L"] = 
            {
                ["weapons"] = 
                {
                    ["GIAT_M621G"] = 
                    {
                        ["hit"] = 0,
                        ["kills"] = 0,
                        ["shot"] = 85,
                        ["numHits"] = 0,
                    }, -- end of ["GIAT_M621G"]
                }, -- end of ["weapons"]
                ["total"] = 740.264,
                ["actions"] = 
                {
                    ["landing"] = 
                    {
                        ["austere"] = 1,
                    }, -- end of ["landing"]
                }, -- end of ["actions"]
                ["inAir"] = 400.134,
            }, -- end of ["SA342L"]
            ["FA-18C_hornet"] = 
            {
                ["total"] = 46122.148,
                ["kills"] = 
                {
                    ["Ground Units"] = 
                    {
                        ["Infantry"] = 11,
                        ["SAM"] = 2,
                        ["total"] = 13,
                    }, -- end of ["Ground Units"]
                    ["Buildings"] = 
                    {
                        ["total"] = 2,
                        ["Static"] = 2,
                    }, -- end of ["Buildings"]
                    ["Helicopters"] = 
                    {
                        ["total"] = 2,
                        ["Utility"] = 2,
                    }, -- end of ["Helicopters"]
                }, -- end of ["kills"]
                ["weapons"] = 
                {
                    ["AGM-88C"] = 
                    {
                        ["numHits"] = 39,
                        ["kills"] = 13,
                        ["shot"] = 4,
                        ["hit"] = 0,
                    }, -- end of ["AGM-88C"]
                    ["AIM-120C"] = 
                    {
                        ["numHits"] = 0,
                        ["kills"] = 0,
                        ["shot"] = 7,
                        ["hit"] = 0,
                    }, -- end of ["AIM-120C"]
                    ["AGM-154C"] = 
                    {
                        ["hit"] = 0,
                        ["kills"] = 2,
                        ["shot"] = 4,
                        ["numHits"] = 11,
                    }, -- end of ["AGM-154C"]
                    ["Mk-82Y"] = 
                    {
                        ["numHits"] = 0,
                        ["kills"] = 0,
                        ["shot"] = 4,
                        ["hit"] = 0,
                    }, -- end of ["Mk-82Y"]
                    ["kamikaze"] = 
                    {
                        ["numHits"] = 2,
                        ["kills"] = 2,
                        ["shot"] = 0,
                        ["hit"] = 0,
                    }, -- end of ["kamikaze"]
                    ["GBU-31(V)3/B"] = 
                    {
                        ["numHits"] = 0,
                        ["kills"] = 0,
                        ["shot"] = 4,
                        ["hit"] = 0,
                    }, -- end of ["GBU-31(V)3/B"]
                }, -- end of ["weapons"]
                ["inAir"] = 33366.785,
                ["actions"] = 
                {
                    ["landing"] = 
                    {
                        ["austere"] = 1,
                        ["airbase"] = 2,
                    }, -- end of ["landing"]
                    ["losses"] = 
                    {
                        ["pilotDeath"] = 1,
                        ["crash"] = 1,
                        ["eject"] = 0,
                    }, -- end of ["losses"]
                    ["LSO"] = 
                    {
                        ["1"] = 0,
                        ["3"] = 2,
                        ["2"] = 1,
                        ["4"] = 0,
                        ["grades"] = 
                        {
                            [1] = "LSO: GRADE:--- : (LLWDIW)  WIRE# 3[BC]",
                        }, -- end of ["grades"]
                    }, -- end of ["LSO"]
                }, -- end of ["actions"]
                ["pvp"] = 
                {
                    ["losses"] = 1,
                }, -- end of ["pvp"]
            }, -- end of ["FA-18C_hornet"]
        }, -- end of ["times"]
        ["joinDate"] = 1595476800,
        ["lastJoin"] = 1611730827,
        ["id"] = 3,
        ["names"] = 
        {
            [1] = "Pilot 300",
            [2] = "Pilot 301",
            [3] = "Trooper",
        }, -- end of ["names"]
    }, -- end of ["8502672f5e3b83d5be49924a5ddc129f"]
} -- end of stats

stats["bb369ece022304521617dea849e36697"]["lastJoin"] = 1611894801
stats["bb369ece022304521617dea849e36697"]["lastJoin"] = 1611894824
stats["bb369ece022304521617dea849e36697"]["lastJoin"] = 1611894837
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["lastJoin"] = 1611896717
stats["756b8f1d03879cd9d696f168c868685e"]["lastJoin"] = 1611896781
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"] = { ["total"] = 0, ["inAir"] = 0, }
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 10
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 10
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8023.262
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15466.551
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 20.005
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 20.005
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8033.267
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15476.556
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 30.01
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 30.01
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8043.272
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15486.561
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 40.017
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 40.017
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8053.279
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15496.568
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 50.02
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 50.02
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8063.282
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15506.571
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 60.028
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 60.028
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8073.29
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15516.579
stats["aea04a1ee754dc16e4d41b78fba43cae"]["lastJoin"] = 1611896868
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 70.029
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 70.029
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8083.291
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15526.58
stats["aea04a1ee754dc16e4d41b78fba43cae"]["lastJoin"] = 1611896872
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 80.036
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 80.036
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8093.298
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15536.587
stats["d3378b4e056070b9bc7af236cf02f151"]["lastJoin"] = 1611896888
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 90.068
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 90.068
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8103.33
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15546.619
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["inAir"] = 100.11
stats["485d8bd5d5fb19beb1e2c6430e4fb966"]["times"]["F-5E-3"]["total"] = 100.11
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["inAir"] = 8113.372
stats["756b8f1d03879cd9d696f168c868685e"]["times"]["FA-18C_hornet"]["total"] = 15556.661
stats["d3378b4e056070b9bc7af236cf02f151"]["times"]["F-5E-3"] = { ["total"] = 0, ["inAir"] = 0, }
stats["d3378b4e056070b9bc7af236cf02f151"]["times"]["F-5E-3"]["inAir"] = 10.042
stats["d3378b4e056070b9bc7af236cf02f151"]["times"]["F-5E-3"]["total"] = 10.042
`

**Comment by Heater711** [comment] 2021-03-12 08:58
Thanks, I will try.

**Closed as completed** 2021-07-16 20:52 UTC
